name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }} # souvent 'ubuntu' ou 'ec2-user'
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/mon_projet_ia_pic
            git pull origin main
            
            # Stopper l'ancien conteneur s'il existe
            docker stop streamlit_app || true
            docker rm streamlit_app || true
            
            # Builder la nouvelle image
            docker build -t streamlit_app .
            
            # Lancer le conteneur (RESTART ALWAYS = Equivalent PM2 pour Docker)
            docker run -d \
              --name streamlit_app \
              --restart always \
              -p 8501:8501 \
              streamlit_app